### ISSUE TITLE
Preview 4 monthly performance report feedback/TODO

### ISSUE THREAD

**Issue by dakersnar** [dotnet/performance#2412]
Here is a TODO list for next month, based on open discussions and user feedback. Will be updated as more feedback comes in.
- [ ] Discuss testing of nativeaot, clarify in instructions which users are responsible for running this
- [ ] Clarify that two previews can still be run back to back if the resume feature is not wanted
- [ ] Add a row for ubuntu 22.X to the table
- [ ] Add automatic architecture detection to the instructions once we agree on the robustness of the feature
- [ ] Debug preview 4 "arm" architecture problem

**Comment by dakersnar** [comment]
The "arm" architecture problem is being tracked here: https://github.com/dotnet/msbuild/issues/7643

**Comment by dakersnar** [comment]
Added some feedback from preview 5
