### ISSUE TITLE
Road to BenchmarkDotNet

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#26]
This is a list of requirements that need to be met before we switch from xunit-performance to BenchmarkDotNet. 

Missing features:
- [x]  https://github.com/dotnet/BenchmarkDotNet/issues/587 "Support netcoreapp2.1" (fixed by @eerhardt, was part of `0.10.11` release)
- [x]  https://github.com/dotnet/BenchmarkDotNet/issues/256 https://github.com/dotnet/BenchmarkDotNet/issues/350 https://github.com/dotnet/BenchmarkDotNet/pull/754 "Per-method parameterization" - sth what xunit offers with `[InlineData]` and `[MemberData]`  (fixed by @adamsitnik, was part of `0.10.14` release)
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/652 support generic benchmark types (fixed by @adamsitnik, was part of `0.10.13` release)
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/175 "Add .NET Core support for Diagnostics package" - consume the .NET Standard TraceEvent lib and allow to use it in .NET Core apps (fixed by @adamsitnik, **will be** part of `0.11.00` release)
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/698 ".NET Standard 2.0, support" (fixed by @adamsitnik, **will be** part of `0.11.00` release)
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/701 "Implement BenchView exporter"
- [ ] https://github.com/dotnet/BenchmarkDotNet/issues/715 "Scenarios support - run given exe as benchmark, gather multiple results" - we need it for JitBench, the Roslyn team has an initial implementation that we could use

Performance (the tool needs to be fast to run as part of CI):
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/606 "Improve Memory Diagnoser" - BDN requir**ed** one extra process run to get the memory statistics, I have changed the architecture to require only one extra iteration. We need one extra iteration because for desktop .NET we are using `AppDomain.MonitoringIsEnabled` which adds an extra overhead. So we run the benchmarks without overhead, measure time, enable monitoring and run one extra iteration to get the memory statistics (fixed by @adamsitnik, was part of `0.10.12` release)
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/543 "Run Disassembly Diagnoser without extra run" - BDN requir**ed** one extra process run to get the disassembly, I have changed the architecture to synchronize parent and child processes and get the disassembly after running the benchmarks, but before quiting the process (fixed by @adamsitnik, was part of `0.10.12` release)
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/699 "Generate one executable per runtime settings" BDN us**ed** to build an extra exe per benchmark. It was taking a **lot** of time. , I have changed the architecture, now it groups the benchmarks by runtime settings (framework/JIT/GC etc) and builds in parallel one exe for the entire group of benchmarks. For `BenchmarkDotNet.Samples` project with 650 benchmarks it used to take 1h to build the extra exes. Now its's 13s on my PC (fixed by @adamsitnik, **will be** part of `0.11.00` release)
- [ ] https://github.com/dotnet/BenchmarkDotNet/issues/704 "Add an optional way to configure storage to remember the PerfectInvocationCount, IterationCount and UnrollFactor" By default BDN uses a heuristic to find perfect invocation and iteration count. For CI scenarios we should remember these values, I estimate that it should save us 20-25% of time.
- [ ] https://github.com/dotnet/BenchmarkDotNet/issues/716 Allow to optionally run benchmarks in Parallel. 

Private runtimes support (BenchmarkDotNet compiles new exe, so it needs to know how to work with private builds):
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/648 "BenchmarkDotNet requires dotnet cli toolchain to be installed". Prior joining MS I had no idea that you run .NET Core apps without adding dotnet cli to the PATH. Now it's optional and user can provide path to dotnet cli which should be used (fixed by @adamsitnik, was part of `0.10.13` release)
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/643 "BenchmarkDotNet should respect `LangVersion` project setting" - just copy it to the auto-generated project (fixed by @adamsitnik, was part of `0.10.13` release)
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/706 "Support private builds of .NET Runtime"  - @vitek-karas needed to measure the perf difference after his recent NGEN changes. He wanted to compare the existing .NET Framework with his private build of CLR. This feature simply sends the provided version as `COMPLUS_Version` env var to the benchmarked process and allows to benchmark private desktop CLR builds.  (fixed by @adamsitnik, was part of `0.10.14` release)
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/700 "Support private CoreCLR and CoreFX buids" - users can now use ANY CoreCLR and CoreFX builds for benchmarking. Uses dotnet cli to publish self-contained app, works on Windows, Linux and Mac. (fixed by @adamsitnik, **will be** part of `0.11.00` release)
- [x] https://github.com/dotnet/BenchmarkDotNet/issues/718 CoreRT support.

Verification:
- [ ] https://github.com/dotnet/BenchmarkDotNet/issues/714 Test BenchmarkDotNet against unstable/multimodal benchmarks from CoreCLR/CoreFX repo provided by @AndyAyersMS .

I am tagging the Perf Team and the people who are interested in the progress:
@jorive @valenis @adiaaida @DrewScoggins @brianrob 
@ViktorHofer @danmosemsft @eerhardt 
@AndyAyersMS @JosephTremoulet 
@davidfowl @DamianEdwards

**Comment by adamsitnik** [comment]
Closing as now we have all micro-benchmarks ported to BenchmarkDotNet and working on all OSes and all architectures.
